name: Build Julia Portable Artifact

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Julia version (e.g., 1.10.4)'
        required: true
        default: '1.10.4'
  push:
    tags:
      - 'portable-*'

jobs:
  build-portable:
    runs-on: ubuntu-latest
    steps:
      - name: Compute URLs
        id: meta
        run: |
          ver='${{ github.event.inputs.version || '1.10.4' }}'
          echo "ver=$ver" >> $GITHUB_OUTPUT
          arch=$(uname -m)
          if [ "$arch" = x86_64 ]; then
            path="bin/linux/x64/$(echo $ver | awk -F. '{print $1 "." $2}')"
            file="julia-${ver}-linux-x86_64.tar.gz"
          else
            path="bin/linux/aarch64/$(echo $ver | awk -F. '{print $1 "." $2}')"
            file="julia-${ver}-linux-aarch64.tar.gz"
          fi
          echo "path=$path" >> $GITHUB_OUTPUT
          echo "file=$file" >> $GITHUB_OUTPUT
      - name: Download Julia tarball
        run: |
          url1="https://julialang-s3.julialang.org/${{ steps.meta.outputs.path }}/${{ steps.meta.outputs.file }}"
          url2="https://mirrors.ustc.edu.cn/julia-releases/${{ steps.meta.outputs.path }}/${{ steps.meta.outputs.file }}"
          curl -fL "$url1" -o julia-portable.tar.gz || curl -fL "$url2" -o julia-portable.tar.gz
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: julia-portable-${{ steps.meta.outputs.ver }}
          path: julia-portable.tar.gz
      - name: Upload release asset
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: julia-portable.tar.gz